### ISSUE TITLE
Feedback for "Use Custom Domain in Identity Authentication"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-identity-authentication#20]
https://help.sap.com/docs/identity-authentication/identity-authentication/use-custom-domain-in-identity-authentication

How to read "_The custom domain configuration is enabled with the upgrade of Identity Authentication. Identity Authentication has production releases (bi-weekly updates) planned every second Wednesday, 10:00 UTC. There are also immediate updates in case of fixes required for bugs that affect productive application operations, or due to urgent security fixes. For more information on the upgrade calendar of the service, see [What's New for Identity Authentication](https://help.sap.com/docs/identity-authentication/identity-authentication/what-s-new-for-identity-authentication)._"
Especially the part " _Identity Authentication has production releases (bi-weekly updates) planned every second Wednesday, 10:00 UTC_." Every second Wednesday on what? Could you please clarify and precise the dates? Even here [https://help.sap.com/docs/identity-authentication/identity-authentication/updates-and-notifications?q=weekly](https://help.sap.com/docs/identity-authentication/identity-authentication/updates-and-notifications?q=weekly) we do not get further clarity on when an update happens. Also checking the What's New section, no pattern can be observed.

**Comment by ValAta** [comment]
Hi @mar-hol ,
Thanks for your question. 
The planned updates are as described. Although they are planned, sometimes due to technical or other issues, these releases could be delayed.  Sometimes, as we state, there could be off-cycle releases.  When there is a release, this information is announced in the What's new section. I agree that it's not very convenient to refresh the page, to see if there is something new. 
However, you can subscribe for the What's new viewer page of Identity Authentication at https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Identity%2520Authentication&locale=en-US&version=Cloud. Just choose the Subscribe button that is at the top of the page. Thus, every time there is a release you will receive a notification via email.
Best regards,
Valentin

**Comment by mar-hol** [comment]
https://people.sap.com/mar-hol
