### ISSUE TITLE
Feedback for "User Registration"

### ISSUE THREAD

**Issue by nicoschoenteich** [SAP-docs/btp-identity-authentication#9]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/0aa433c741a24df9ac2b3a5faca202de.html

Hi all,

I did some research and I believe there are three different API endpoint for the user management:

1. `/service/scim/Users` (deprecated, see [documentation](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/cea87780bee94c6994b8005c6d6a4815.html))
1. `/service/users` (see [documentation](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/0aa433c741a24df9ac2b3a5faca202de.html)) 
1. `/scim/Users` (see [API Business Hub](https://api.sap.com/api/IAS_SCIM/resource))

I have a few questions related to that:

- Why is the third API (`/scim/Users`) not in the documentation and only in the API Business Hub?
- Is there an official name for the third API (`/scim/Users`)? The documentation says that the `SCIM REST API` is deprecated. It is very confusing that there are two APIs with the keyword `scim` in it. The naming of the APIs could be better and should perhaps be reworked.
- Why is there no central page that lists the different APIs and compares them? I had to find out the hard way that `/scim/Users` doesn't automatically sends an activation email to user, but `/service/users` does. This should be in the docs.

Looking forward to hearing back!

Best Regards, Nico

**Comment by nicoschoenteich** [comment]
I just found another API in the [API Business Hub](https://api.sap.com/api/IdDS_SCIM/resource) which seems to be very similar to the [third API I listed above](https://api.sap.com/api/IAS_SCIM/resource) (as `/Users` gets prefixed with `scim` when you click on "Try Out"), which makes things even more complicated.

**Comment by ValAta** [comment]
Hi @nicoschoenteich , 
Thanks for your question. I need to gather some additional information and I'll get back to you with the answer.
Best regards,
Valentin

**Comment by nicoschoenteich** [comment]
https://people.sap.com/nicolai.geburek

**Comment by ValAta** [comment]
Hi @nicoschoenteich,
Back to your questions:

- 1 is the deprecated API, and 3 (the [Identity Directory API](https://api.sap.com/api/IAS_SCIM/overview) ) is the successor of 1. 3 is in the SAP API Business Hub only, because SAP targets to use this platform as the place for its APIs. So all new API's should be only there. 

- 2 is a different API. 1 and 3 are according to the SCIM REST API protocol. 

- We prepared a migration document comparing the two APIs - the deprecated and successor. You can find it at: https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/106dbe0c3fa9473396eb204acedebe5f.html?version=Cloud
Best regards,
Valentin
